### ISSUE TITLE
 Sub folder in web path 

### ISSUE THREAD

**Issue by markstien** [Stexxe/ktor_webview#1]
what if i want to hold the entire folder  with sub folder ?

Is there any just copy the dir?

**Comment by sobaee** [comment]
Hello developer

Did you managed to make the app be able to deal with subfolders in assets/web folder?


If we try to add a subfolder, the app directly crashs

Please help

**Comment by markstien** [comment]
> Hello developer
> 
> Did you managed to make the app be able to deal with subfolders in assets/web folder?
> 
> If we try to add a subfolder, the app directly crashs
> 
> Please help

yes i did that.  but it's been a long time , can i see your code?

**Comment by Stexxe** [comment]
Do you want me to fix this in repository and upgrade to the latest version of Ktor?

**Comment by sobaee** [comment]
> Do you want me to fix this in repository and upgrade to the latest version of Ktor?

Yes, please
I appreciate that
Could you do it?

**Comment by Stexxe** [comment]
Fixed in bfd06847d0a371462b1f9e5f3992b6c835ab5323. Please check.

**Comment by sobaee** [comment]
> Fixed in [bfd0684](https://github.com/Stexxe/ktor_webview/commit/bfd06847d0a371462b1f9e5f3992b6c835ab5323). Please check.

I appreciate that 
I will try

**Comment by sobaee** [comment]
> Fixed in [bfd0684](https://github.com/Stexxe/ktor_webview/commit/bfd06847d0a371462b1f9e5f3992b6c835ab5323). Please check.

Thanks a lot

No more crashs on adding subfolders

It works well with many local html sites

But I have that a html website which works well by the way in any internet browser after I open your app and the srever created (http://127.0.0.1:3333/static/index.html), but inside your app webview only the website background appears

I don't what is the problem

Could I share with you in private my local html website to see what is the issue, please?
It's for the benefit of the community and to make the life easier

**Comment by Stexxe** [comment]
Yes, please share your website files.

**Comment by sobaee** [comment]
Thanks

Here it is:
https://drive.google.com/file/d/16Jn5NNzfCPagcCMT0uLCpJbVsnsrigkz/view?usp=drivesdk

**Comment by Stexxe** [comment]
I see the following in an Android emulator:
![Screen Shot 2022-10-11 at 7 10 32 PM](https://user-images.githubusercontent.com/7986337/195144232-f197aa66-f9ad-466f-a4a0-e0eb3d07b165.png)

**Comment by sobaee** [comment]
> I see the following in an Android emulator: ![Screen Shot 2022-10-11 at 7 10 32 PM](https://user-images.githubusercontent.com/7986337/195144232-f197aa66-f9ad-466f-a4a0-e0eb3d07b165.png)

Yes
Please press the big "X"
The page should be under it

**Comment by Stexxe** [comment]
I've fixed it by enabling local storage for the web view (eebf575f3a9405fa1b212a0892626b4e28d86b99).

**Comment by sobaee** [comment]
> I've fixed it by enabling local storage for the web view ([eebf575](https://github.com/Stexxe/ktor_webview/commit/eebf575f3a9405fa1b212a0892626b4e28d86b99)).

Many thanks bro.


Could you please add this email as developer to the github of this app:
arunkrishna007arun@gmail.com

 He is a friend of mine, he could add something good this app, and he will not have to download the masterzip everytime from github

Thanks a lot

**Comment by Stexxe** [comment]
No. He can create pull requests if he wants.

**Comment by sobaee** [comment]
Okay, thanks 🙏

**Comment by sobaee** [comment]
Hello Stexxe

Could you please fix this error:


java.lang.IllegalArgumentException: Can only download HTTP/HTTPS URIs: blob:http://127.0.0.1:3333/68c02cb3-0bb2-4e85-9305-7c39af8d1555

**Comment by sobaee** [comment]
Hello Stexxe

This link:
https://drive.google.com/open?id=1xIoDKjFy0SuXtHklqo-DIVmLtiemfGuf

We have added things to your source code like storage permissions and download function but there was an issue with saving function maybe in the website itself (converting the blob to base64 in java script!!).

I know this could be a lot of work, but
Could you please try to fix this out?
